title:              Viacheslav Dziadok's Blog
email:              viacheslav.v.dziadok@gmail.com
description:        A personal blog developed using Blog Theme by Start Bootstrap
author:             Viacheslav Dziadok
baseurl:            ""
url:                "https://viacheslav.dziadok.netlify.app"

# Social Profiles
twitter_username:   Slava_Dziadok
github_username:    ViacheslavDziadok
facebook_username:  viacheslav.dziadok
instagram_username: viacheslav.dziadok
linkedin_username:  viacheslav-dziadok

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
